# Generated by Django 6.0.4 on 2026-05-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_category_id_alter_project_id_alter_worklog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='サブカテゴリ名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.AddField(
            model_name='worklog',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.subcategory', verbose_name='サブカテゴリ'),
        ),
    ]
